/**
 * Do not edit directly
 * Generated on Mon, 12 Dec 2022 10:14:06 GMT
 */

const spacing = {
  "1": "0.25rem",
  "2": "0.5rem",
  "3": "0.75rem",
  "4": "1rem",
  "5": "1.25rem",
  "6": "1.5rem",
  "7": "1.75rem",
  "8": "2rem",
  "9": "2.25rem",
  "10": "2.5rem",
  "11": "2.75rem",
  "12": "3rem",
  "13": "3.5rem",
  "14": "4rem",
}

const borderRadius = {
  default: 4,
  circle: "50%",
}

const color = {
  blue: {
    "50": "#F7F9FE",
    "100": "#E1EBFD",
    "200": "#ACC7FA",
    "300": "#82ABF7",
    "400": "#568DF4",
    "500": "#276EF1",
    "600": "#0D4FCA",
    "700": "#0B44AC",
    "800": "#093890",
    "900": "#072A69",
  },
  red: {
    "50": "#fef7f7",
    "100": "#fbe4e4",
    "200": "#f4acac",
    "300": "#ee8080",
    "400": "#e74f4f",
    "500": "#c03434",
    "600": "#992a2a",
    "700": "#852424",
    "800": "#721f1f",
    "900": "#571717",
  },
  green: {
    "50": "#f5fbf9",
    "100": "#d6f0e7",
    "200": "#7ccfb3",
    "300": "#33b488",
    "400": "#009762",
    "500": "#00774e",
    "600": "#005f3e",
    "700": "#005336",
    "800": "#00462e",
    "900": "#003523",
  },
  yellow: {
    "50": "#fffae1",
    "100": "#FFDA68",
    "200": "#E2B73E",
    "300": "#C4992A",
    "400": "#A77C18",
    "500": "#8B6005",
    "600": "#704C00",
    "700": "#624200",
    "800": "#533800",
    "900": "#3f2b00",
  },
  slate: {
    "50": "#f8f9fa",
    "100": "#e9eaee",
    "200": "#babecb",
    "300": "#9aa0b3",
    "400": "#7b849c",
    "500": "#5d6785",
    "600": "#465173",
    "700": "#3c4764",
    "800": "#333c56",
    "900": "#272d41",
  },
  grey: {
    "50": "#f9f9f9",
    "100": "#e9e9e9",
    "200": "#bfbfbf",
    "300": "#a0a0a0",
    "400": "#848484",
    "500": "#686868",
    "600": "#535353",
    "700": "#474747",
    "800": "#3d3d3d",
    "900": "#2e2e2e",
  },
  standard: {
    white: "#ffffff",
    black: "#000000",
  },
  brand: {
    primary: {
      "50": "#F7F9FE",
      "100": "#E1EBFD",
      "200": "#ACC7FA",
      "300": "#82ABF7",
      "400": "#568DF4",
      "500": "#276EF1",
      "600": "#0D4FCA",
      "700": "#0B44AC",
      "800": "#093890",
      "900": "#072A69",
    },
    secondary: {
      "50": "#f8f9fa",
      "100": "#e9eaee",
      "200": "#babecb",
      "300": "#9aa0b3",
      "400": "#7b849c",
      "500": "#5d6785",
      "600": "#465173",
      "700": "#3c4764",
      "800": "#333c56",
      "900": "#272d41",
    },
  },
  skin: {
    "1base": "#FFCAA4",
    "1shadow": "#F5B896",
    "2base": "#EBA687",
    "2shadow": "#E29B7B",
    "3base": "#D98F6F",
    "3shadow": "#CE8361",
    "4base": "#BF7657",
    "4shadow": "#AF6D53",
    "5base": "#9F634F",
    "5shadow": "#8B5544",
    "6base": "#764738",
    "6shadow": "#633D32",
  },
  base: {
    canvas: {
      default: "#ffffff",
      alt: "#f9f9f9",
      backdrop: "#e9e9e9",
      brandLight: "#F7F9FE",
      inverse: "#3d3d3d",
      overlay: "rgba(#3d3d3d, 0.8)",
    },
    content: {
      default: "#474747",
      dark: "#2e2e2e",
      light: "#848484",
      brand: "#276EF1",
      inverse: "#ffffff",
    },
    divider: {
      light: "#f9f9f9",
      medium: "#e9e9e9",
      dark: "#bfbfbf",
      inverse: "#ffffff",
      brand: "#276EF1",
    },
  },
  interaction: {
    main: {
      default: "#276EF1",
      hover: "#0D4FCA",
      active: "#0B44AC",
    },
    "main-light": {
      default: "#F7F9FE",
      hover: "#E1EBFD",
      active: "#ACC7FA",
    },
    sub: {
      default: "#5d6785",
      hover: "#465173",
      active: "#3c4764",
    },
    "sub-light": {
      default: "#f8f9fa",
      hover: "#e9eaee",
      active: "#babecb",
    },
    critical: {
      default: "#c03434",
      hover: "#992a2a",
      active: "#852424",
    },
    "critical-light": {
      default: "#fef7f7",
      hover: "#fbe4e4",
      active: "#f4acac",
    },
    warning: {
      default: "#FFDA68",
      hover: "#E2B73E",
      active: "#C4992A",
    },
    "warning-light": {
      default: "#fffae1",
      hover: "#FFDA68",
      active: "#E2B73E",
    },
    success: {
      default: "#00774e",
      hover: "#005f3e",
      active: "#005336",
    },
    "success-light": {
      default: "#f5fbf9",
      hover: "#d6f0e7",
      active: "#7ccfb3",
    },
    "neutral-light": {
      default: "#f9f9f9",
      hover: "#e9e9e9",
      active: "#bfbfbf",
    },
    muted: {
      main: {
        hover: "#F7F9FE",
        active: "#E1EBFD",
      },
      sub: {
        hover: "#f8f9fa",
        active: "#e9eaee",
      },
      critical: {
        hover: "#fef7f7",
        active: "#fbe4e4",
      },
      neutral: {
        hover: "#f9f9f9",
        active: "#e9e9e9",
      },
    },
    tinted: {
      main: {
        hover: "rgba(#276EF1, 0.04)",
        active: "rgba(#276EF1, 0.12)",
      },
      critical: {
        hover: "rgba(#c03434, 0.04)",
        active: "rgba(#c03434, 0.12)",
      },
      dark: {
        hover: "rgba(#000000, 0.1)",
        active: "rgba(#000000, 0.2)",
      },
      light: {
        hover: "rgba(#ffffff, 0.1)",
        active: "rgba(#ffffff, 0.2)",
      },
    },
    support: {
      unselected: "#a0a0a0",
      selected: "#686868",
      "unselected-dark": "#686868",
      disabled: "#e9e9e9",
      "disabled-content": "#a0a0a0",
      placeholder: "#a0a0a0",
    },
    links: {
      default: "#276EF1",
      hover: "#0D4FCA",
      "dark-default": "#474747",
      "dark-hover": "#2e2e2e",
      "inverse-default": "#ffffff",
      "inverse-hover": "#e9e9e9",
    },
  },
  utility: {
    feedback: {
      info: "#276EF1",
      "info-light": "#F7F9FE",
      warning: "#FFDA68",
      "warning-light": "#fffae1",
      success: "#00774e",
      "success-light": "#f5fbf9",
      critical: "#c03434",
      "critical-light": "#fef7f7",
    },
    "focus-default": "#276EF1",
    "focus-inverse": "#ffffff",
    "input-prefilled": "#fffae1",
    ui: "#ffffff",
    "ui-clear": "rgba(#ffffff,0)",
  },
}

const shadow = {
  small: "0px 0px 10px 0px rgba(191, 191, 191, 0.5)",
  medium: "0px 0px 20px 0px rgba(104, 104, 104, 0.3)",
}

const typography = {
  fontFamilies: {
    inter: "Inter",
    ibmplexmono: "IBM Plex Mono",
  },
  lineHeights: {
    "3": "0.75rem",
    "4": "1rem",
    "5": "1.25rem",
    "6": "1.5rem",
    "7": "1.75rem",
    "8": "2rem",
    "9": "2.25rem",
    "10": "2.5rem",
    "11": "2.75rem",
    "12": "3rem",
    "13": "3.25rem",
    "14": "3.5rem",
    "15": "3.75rem",
    "16": "4rem",
    "17": "4.25rem",
    "18": "4.5rem",
  },
  fontWeights: {
    light: "Light",
    normal: "Regular",
    medium: "Medium",
    semibold: "Semi Bold",
    bold: "Bold",
  },
  fontSize: {
    "2xs": "0.625rem",
    xs: "0.75rem",
    sm: "0.875rem",
    md: "1rem",
    lg: "1.125rem",
    xl: "1.25rem",
    "2xl": "1.5rem",
    "3xl": "1.75rem",
    "4xl": "2rem",
    "5xl": "2.25rem",
    "6xl": "2.5rem",
    "7xl": "2.75rem",
    "8xl": "3rem",
    "9xl": "3.5rem",
    "10xl": "4rem",
    "11xl": "4.5rem",
  },
  letterSpacing: {
    "1": "-0.6%",
    "2": "-1.4%",
    "3": "-1.9%",
    "4": "-2.2%",
    wide: "8%",
    normal: 0,
  },
  paragraphSpacing: {
    "0": 0,
  },
  "responsive-display": {
    "heavy-1280": {
      fontFamily: "Inter",
      fontWeight: "Bold",
      lineHeight: "4.5rem",
      fontSize: "4rem",
      letterSpacing: "-2.2%",
      paragraphSpacing: 0,
      textCase: "none",
      textDecoration: "none",
    },
    "heavy-480": {
      fontFamily: "Inter",
      fontWeight: "Bold",
      lineHeight: "4rem",
      fontSize: "3.5rem",
      letterSpacing: "-2.2%",
      paragraphSpacing: 0,
      textCase: "none",
      textDecoration: "none",
    },
    heavy: {
      fontFamily: "Inter",
      fontWeight: "Semi Bold",
      lineHeight: "3rem",
      fontSize: "2.5rem",
      letterSpacing: "-2.2%",
      paragraphSpacing: 0,
      textCase: "none",
      textDecoration: "none",
    },
    "light-1280": {
      fontFamily: "Inter",
      fontWeight: "Light",
      lineHeight: "4.5rem",
      fontSize: "4rem",
      letterSpacing: "-2.2%",
      paragraphSpacing: 0,
      textCase: "none",
      textDecoration: "none",
    },
    "light-480": {
      fontFamily: "Inter",
      fontWeight: "Light",
      lineHeight: "4rem",
      fontSize: "3.5rem",
      letterSpacing: "-2.2%",
      paragraphSpacing: 0,
      textCase: "none",
      textDecoration: "none",
    },
    light: {
      fontFamily: "Inter",
      fontWeight: "Light",
      lineHeight: "3rem",
      fontSize: "2.5rem",
      letterSpacing: "-2.2%",
      paragraphSpacing: 0,
      textCase: "none",
      textDecoration: "none",
    },
  },
  "responsive-heading": {
    "heavy-1280": {
      fontFamily: "Inter",
      fontWeight: "Semi Bold",
      lineHeight: "3.5rem",
      fontSize: "3rem",
      letterSpacing: "-2.2%",
      paragraphSpacing: 0,
      textCase: "none",
      textDecoration: "none",
    },
    "heavy-480": {
      fontFamily: "Inter",
      fontWeight: "Semi Bold",
      lineHeight: "3rem",
      fontSize: "2.5rem",
      letterSpacing: "-2.2%",
      paragraphSpacing: 0,
      textCase: "none",
      textDecoration: "none",
    },
    heavy: {
      fontFamily: "Inter",
      fontWeight: "Semi Bold",
      lineHeight: "2.5rem",
      fontSize: "2rem",
      letterSpacing: "-2.2%",
      paragraphSpacing: 0,
      textCase: "none",
      textDecoration: "none",
    },
    "light-1280": {
      fontFamily: "Inter",
      fontWeight: "Light",
      lineHeight: "3.5rem",
      fontSize: "3rem",
      letterSpacing: "-2.2%",
      paragraphSpacing: 0,
      textCase: "none",
      textDecoration: "none",
    },
    "light-480": {
      fontFamily: "Inter",
      fontWeight: "Light",
      lineHeight: "3rem",
      fontSize: "2.5rem",
      letterSpacing: "-2.2%",
      paragraphSpacing: 0,
      textCase: "none",
      textDecoration: "none",
    },
    light: {
      fontFamily: "Inter",
      fontWeight: "Light",
      lineHeight: "2.5rem",
      fontSize: "2rem",
      letterSpacing: "-2.2%",
      paragraphSpacing: 0,
      textCase: "none",
      textDecoration: "none",
    },
  },
  h1: {
    fontFamily: "Inter",
    fontWeight: "Semi Bold",
    lineHeight: "3rem",
    fontSize: "2.5rem",
    letterSpacing: "-2.2%",
    paragraphSpacing: 0,
    textCase: "none",
    textDecoration: "none",
  },
  h2: {
    fontFamily: "Inter",
    fontWeight: "Semi Bold",
    lineHeight: "2.75rem",
    fontSize: "2.25rem",
    letterSpacing: "-2.2%",
    paragraphSpacing: 0,
    textCase: "none",
    textDecoration: "none",
  },
  h3: {
    fontFamily: "Inter",
    fontWeight: "Bold",
    lineHeight: "2.25rem",
    fontSize: "1.75rem",
    letterSpacing: "-1.9%",
    paragraphSpacing: 0,
    textCase: "none",
    textDecoration: "none",
  },
  h4: {
    fontFamily: "Inter",
    fontWeight: "Semi Bold",
    lineHeight: "2rem",
    fontSize: "1.5rem",
    letterSpacing: "-1.9%",
    paragraphSpacing: 0,
    textCase: "none",
    textDecoration: "none",
  },
  h5: {
    fontFamily: "Inter",
    fontWeight: "Semi Bold",
    lineHeight: "1.75rem",
    fontSize: "1.25rem",
    letterSpacing: "-1.4%",
    paragraphSpacing: 0,
    textCase: "none",
    textDecoration: "none",
  },
  h6: {
    fontFamily: "Inter",
    fontWeight: "Medium",
    lineHeight: "1.5rem",
    fontSize: "1.125rem",
    letterSpacing: "-1.4%",
    paragraphSpacing: 0,
    textCase: "none",
    textDecoration: "none",
  },
  "subhead-1": {
    fontFamily: "Inter",
    fontWeight: "Medium",
    lineHeight: "1.5rem",
    fontSize: "1rem",
    letterSpacing: "-0.6%",
    paragraphSpacing: 0,
    textCase: "none",
    textDecoration: "none",
  },
  "subhead-2": {
    fontFamily: "Inter",
    fontWeight: "Medium",
    lineHeight: "1.25rem",
    fontSize: "0.875rem",
    letterSpacing: 0,
    paragraphSpacing: 0,
    textCase: "none",
    textDecoration: "none",
  },
  "subhead-3": {
    fontFamily: "Inter",
    fontWeight: "Semi Bold",
    lineHeight: "1.5rem",
    fontSize: "0.875rem",
    letterSpacing: "8%",
    paragraphSpacing: 0,
    textCase: "uppercase",
    textDecoration: "none",
  },
  "body-1": {
    fontFamily: "Inter",
    fontWeight: "Regular",
    lineHeight: "1.5rem",
    fontSize: "1rem",
    letterSpacing: "-0.6%",
    paragraphSpacing: 0,
    textCase: "none",
    textDecoration: "none",
  },
  "body-2": {
    fontFamily: "Inter",
    fontWeight: "Regular",
    lineHeight: "1.25rem",
    fontSize: "0.875rem",
    letterSpacing: 0,
    paragraphSpacing: 0,
    textCase: "none",
    textDecoration: "none",
  },
  "body-3": {
    fontFamily: "Inter",
    fontWeight: "Regular",
    lineHeight: "1.75rem",
    fontSize: "1rem",
    letterSpacing: "-0.6%",
    paragraphSpacing: 0,
    textCase: "none",
    textDecoration: "none",
  },
  "caption-1": {
    fontFamily: "Inter",
    fontWeight: "Medium",
    lineHeight: "1rem",
    fontSize: "0.75rem",
    letterSpacing: 0,
    paragraphSpacing: 0,
    textCase: "none",
    textDecoration: "none",
  },
  "caption-2": {
    fontFamily: "Inter",
    fontWeight: "Regular",
    lineHeight: "1rem",
    fontSize: "0.75rem",
    letterSpacing: 0,
    paragraphSpacing: 0,
    textCase: "none",
    textDecoration: "none",
  },
  "code-1": {
    fontFamily: "IBM Plex Mono",
    fontWeight: "Regular",
    lineHeight: "1.25rem",
    fontSize: "0.875rem",
    letterSpacing: 0,
    paragraphSpacing: 0,
    textCase: "none",
    textDecoration: "none",
  },
  "code-2": {
    fontFamily: "IBM Plex Mono",
    fontWeight: "Regular",
    lineHeight: "1rem",
    fontSize: "0.75rem",
    letterSpacing: 0,
    paragraphSpacing: 0,
    textCase: "none",
    textDecoration: "none",
  },
  legal: {
    fontFamily: "Inter",
    fontWeight: "Regular",
    lineHeight: "0.75rem",
    fontSize: "0.625rem",
    letterSpacing: 0,
    paragraphSpacing: 0,
    textCase: "none",
    textDecoration: "none",
  },
  textCase: {
    none: "none",
    uppercase: "uppercase",
  },
  textDecoration: {
    none: "none",
  },
}

const borderWidth = {
  default: 1,
  focus: 4,
}

export {
  spacing, 
  borderRadius, 
  color, 
  shadow, 
  typography, 
  borderWidth
};
