/**
 * Do not edit directly
 * Generated on Thu, 22 Dec 2022 16:18:22 GMT
 */

export const textStyles = {
  'responsive-display': {
    'heavy-1280': {
      fontFamily: 'Inter',
      fontWeight: 700,
      lineHeight: '4.5rem',
      fontSize: '4rem',
      letterSpacing: '-0.022em',
    },
    'heavy-480': {
      fontFamily: 'Inter',
      fontWeight: 700,
      lineHeight: '4rem',
      fontSize: '3.5rem',
      letterSpacing: '-0.022em',
    },
    heavy: {
      fontFamily: 'Inter',
      fontWeight: 600,
      lineHeight: '3rem',
      fontSize: '2.5rem',
      letterSpacing: '-0.022em',
    },
    'light-1280': {
      fontFamily: 'Inter',
      fontWeight: 300,
      lineHeight: '4.5rem',
      fontSize: '4rem',
      letterSpacing: '-0.022em',
    },
    'light-480': {
      fontFamily: 'Inter',
      fontWeight: 300,
      lineHeight: '4rem',
      fontSize: '3.5rem',
      letterSpacing: '-0.022em',
    },
    light: {
      fontFamily: 'Inter',
      fontWeight: 300,
      lineHeight: '3rem',
      fontSize: '2.5rem',
      letterSpacing: '-0.022em',
    },
  },
  'responsive-heading': {
    'heavy-1280': {
      fontFamily: 'Inter',
      fontWeight: 600,
      lineHeight: '3.5rem',
      fontSize: '3rem',
      letterSpacing: '-0.022em',
    },
    'heavy-480': {
      fontFamily: 'Inter',
      fontWeight: 600,
      lineHeight: '3rem',
      fontSize: '2.5rem',
      letterSpacing: '-0.022em',
    },
    heavy: {
      fontFamily: 'Inter',
      fontWeight: 600,
      lineHeight: '2.5rem',
      fontSize: '2rem',
      letterSpacing: '-0.022em',
    },
    'light-1280': {
      fontFamily: 'Inter',
      fontWeight: 300,
      lineHeight: '3.5rem',
      fontSize: '3rem',
      letterSpacing: '-0.022em',
    },
    'light-480': {
      fontFamily: 'Inter',
      fontWeight: 300,
      lineHeight: '3rem',
      fontSize: '2.5rem',
      letterSpacing: '-0.022em',
    },
    light: {
      fontFamily: 'Inter',
      fontWeight: 300,
      lineHeight: '2.5rem',
      fontSize: '2rem',
      letterSpacing: '-0.022em',
    },
  },
  h1: {
    fontFamily: 'Inter',
    fontWeight: 600,
    lineHeight: '3rem',
    fontSize: '2.5rem',
    letterSpacing: '-0.022em',
  },
  h2: {
    fontFamily: 'Inter',
    fontWeight: 600,
    lineHeight: '2.75rem',
    fontSize: '2.25rem',
    letterSpacing: '-0.022em',
  },
  h3: {
    fontFamily: 'Inter',
    fontWeight: 700,
    lineHeight: '2.25rem',
    fontSize: '1.75rem',
    letterSpacing: '-0.019em',
  },
  h4: {
    fontFamily: 'Inter',
    fontWeight: 600,
    lineHeight: '2rem',
    fontSize: '1.5rem',
    letterSpacing: '-0.019em',
  },
  h5: {
    fontFamily: 'Inter',
    fontWeight: 600,
    lineHeight: '1.75rem',
    fontSize: '1.25rem',
    letterSpacing: '-0.014em',
  },
  h6: {
    fontFamily: 'Inter',
    fontWeight: 500,
    lineHeight: '1.5rem',
    fontSize: '1.125rem',
    letterSpacing: '-0.014em',
  },
  'subhead-1': {
    fontFamily: 'Inter',
    fontWeight: 500,
    lineHeight: '1.5rem',
    fontSize: '1rem',
    letterSpacing: '-0.006em',
  },
  'subhead-2': {
    fontFamily: 'Inter',
    fontWeight: 500,
    lineHeight: '1.25rem',
    fontSize: '0.875rem',
    letterSpacing: 0,
  },
  'subhead-3': {
    fontFamily: 'Inter',
    fontWeight: 600,
    lineHeight: '1.5rem',
    fontSize: '0.875rem',
    letterSpacing: '0.080em',
    textTransform: 'uppercase',
  },
  'body-1': {
    fontFamily: 'Inter',
    fontWeight: 400,
    lineHeight: '1.5rem',
    fontSize: '1rem',
    letterSpacing: '-0.006em',
  },
  'body-2': {
    fontFamily: 'Inter',
    fontWeight: 400,
    lineHeight: '1.25rem',
    fontSize: '0.875rem',
    letterSpacing: 0,
  },
  'body-3': {
    fontFamily: 'Inter',
    fontWeight: 400,
    lineHeight: '1.75rem',
    fontSize: '1rem',
    letterSpacing: '-0.006em',
  },
  'caption-1': {
    fontFamily: 'Inter',
    fontWeight: 500,
    lineHeight: '1rem',
    fontSize: '0.75rem',
    letterSpacing: 0,
  },
  'caption-2': {
    fontFamily: 'Inter',
    fontWeight: 400,
    lineHeight: '1rem',
    fontSize: '0.75rem',
    letterSpacing: 0,
  },
  'code-1': {
    fontFamily: 'IBM Plex Mono',
    fontWeight: 400,
    lineHeight: '1.25rem',
    fontSize: '0.875rem',
    letterSpacing: 0,
  },
  'code-2': {
    fontFamily: 'IBM Plex Mono',
    fontWeight: 400,
    lineHeight: '1rem',
    fontSize: '0.75rem',
    letterSpacing: 0,
  },
  legal: {
    fontFamily: 'Inter',
    fontWeight: 400,
    lineHeight: '0.75rem',
    fontSize: '0.625rem',
    letterSpacing: 0,
  },
}
