/**
 * Do not edit directly
 * Generated on Tue, 13 Dec 2022 09:50:19 GMT
 */

export const textStyles =  {
  "responsive-display": {
    "heavy-1280": {
      fontFamily: "Inter",
      fontWeight: 700,
      lineHeight: "4.5rem",
      fontSize: "4rem",
      letterSpacing: "-0.022em",
      paragraphSpacing: 0,
      textCase: "none",
      textDecoration: "none",
    },
    "heavy-480": {
      fontFamily: "Inter",
      fontWeight: 700,
      lineHeight: "4rem",
      fontSize: "3.5rem",
      letterSpacing: "-0.022em",
      paragraphSpacing: 0,
      textCase: "none",
      textDecoration: "none",
    },
    heavy: {
      fontFamily: "Inter",
      fontWeight: 600,
      lineHeight: "3rem",
      fontSize: "2.5rem",
      letterSpacing: "-0.022em",
      paragraphSpacing: 0,
      textCase: "none",
      textDecoration: "none",
    },
    "light-1280": {
      fontFamily: "Inter",
      fontWeight: 300,
      lineHeight: "4.5rem",
      fontSize: "4rem",
      letterSpacing: "-0.022em",
      paragraphSpacing: 0,
      textCase: "none",
      textDecoration: "none",
    },
    "light-480": {
      fontFamily: "Inter",
      fontWeight: 300,
      lineHeight: "4rem",
      fontSize: "3.5rem",
      letterSpacing: "-0.022em",
      paragraphSpacing: 0,
      textCase: "none",
      textDecoration: "none",
    },
    light: {
      fontFamily: "Inter",
      fontWeight: 300,
      lineHeight: "3rem",
      fontSize: "2.5rem",
      letterSpacing: "-0.022em",
      paragraphSpacing: 0,
      textCase: "none",
      textDecoration: "none",
    },
  },
  "responsive-heading": {
    "heavy-1280": {
      fontFamily: "Inter",
      fontWeight: 600,
      lineHeight: "3.5rem",
      fontSize: "3rem",
      letterSpacing: "-0.022em",
      paragraphSpacing: 0,
      textCase: "none",
      textDecoration: "none",
    },
    "heavy-480": {
      fontFamily: "Inter",
      fontWeight: 600,
      lineHeight: "3rem",
      fontSize: "2.5rem",
      letterSpacing: "-0.022em",
      paragraphSpacing: 0,
      textCase: "none",
      textDecoration: "none",
    },
    heavy: {
      fontFamily: "Inter",
      fontWeight: 600,
      lineHeight: "2.5rem",
      fontSize: "2rem",
      letterSpacing: "-0.022em",
      paragraphSpacing: 0,
      textCase: "none",
      textDecoration: "none",
    },
    "light-1280": {
      fontFamily: "Inter",
      fontWeight: 300,
      lineHeight: "3.5rem",
      fontSize: "3rem",
      letterSpacing: "-0.022em",
      paragraphSpacing: 0,
      textCase: "none",
      textDecoration: "none",
    },
    "light-480": {
      fontFamily: "Inter",
      fontWeight: 300,
      lineHeight: "3rem",
      fontSize: "2.5rem",
      letterSpacing: "-0.022em",
      paragraphSpacing: 0,
      textCase: "none",
      textDecoration: "none",
    },
    light: {
      fontFamily: "Inter",
      fontWeight: 300,
      lineHeight: "2.5rem",
      fontSize: "2rem",
      letterSpacing: "-0.022em",
      paragraphSpacing: 0,
      textCase: "none",
      textDecoration: "none",
    },
  },
  h1: {
    fontFamily: "Inter",
    fontWeight: 600,
    lineHeight: "3rem",
    fontSize: "2.5rem",
    letterSpacing: "-0.022em",
    paragraphSpacing: 0,
    textCase: "none",
    textDecoration: "none",
  },
  h2: {
    fontFamily: "Inter",
    fontWeight: 600,
    lineHeight: "2.75rem",
    fontSize: "2.25rem",
    letterSpacing: "-0.022em",
    paragraphSpacing: 0,
    textCase: "none",
    textDecoration: "none",
  },
  h3: {
    fontFamily: "Inter",
    fontWeight: 700,
    lineHeight: "2.25rem",
    fontSize: "1.75rem",
    letterSpacing: "-0.019em",
    paragraphSpacing: 0,
    textCase: "none",
    textDecoration: "none",
  },
  h4: {
    fontFamily: "Inter",
    fontWeight: 600,
    lineHeight: "2rem",
    fontSize: "1.5rem",
    letterSpacing: "-0.019em",
    paragraphSpacing: 0,
    textCase: "none",
    textDecoration: "none",
  },
  h5: {
    fontFamily: "Inter",
    fontWeight: 600,
    lineHeight: "1.75rem",
    fontSize: "1.25rem",
    letterSpacing: "-0.014em",
    paragraphSpacing: 0,
    textCase: "none",
    textDecoration: "none",
  },
  h6: {
    fontFamily: "Inter",
    fontWeight: 500,
    lineHeight: "1.5rem",
    fontSize: "1.125rem",
    letterSpacing: "-0.014em",
    paragraphSpacing: 0,
    textCase: "none",
    textDecoration: "none",
  },
  "subhead-1": {
    fontFamily: "Inter",
    fontWeight: 500,
    lineHeight: "1.5rem",
    fontSize: "1rem",
    letterSpacing: "-0.006em",
    paragraphSpacing: 0,
    textCase: "none",
    textDecoration: "none",
  },
  "subhead-2": {
    fontFamily: "Inter",
    fontWeight: 500,
    lineHeight: "1.25rem",
    fontSize: "0.875rem",
    letterSpacing: 0,
    paragraphSpacing: 0,
    textCase: "none",
    textDecoration: "none",
  },
  "subhead-3": {
    fontFamily: "Inter",
    fontWeight: 600,
    lineHeight: "1.5rem",
    fontSize: "0.875rem",
    letterSpacing: "0.080em",
    paragraphSpacing: 0,
    textCase: "uppercase",
    textDecoration: "none",
  },
  "body-1": {
    fontFamily: "Inter",
    fontWeight: 400,
    lineHeight: "1.5rem",
    fontSize: "1rem",
    letterSpacing: "-0.006em",
    paragraphSpacing: 0,
    textCase: "none",
    textDecoration: "none",
  },
  "body-2": {
    fontFamily: "Inter",
    fontWeight: 400,
    lineHeight: "1.25rem",
    fontSize: "0.875rem",
    letterSpacing: 0,
    paragraphSpacing: 0,
    textCase: "none",
    textDecoration: "none",
  },
  "body-3": {
    fontFamily: "Inter",
    fontWeight: 400,
    lineHeight: "1.75rem",
    fontSize: "1rem",
    letterSpacing: "-0.006em",
    paragraphSpacing: 0,
    textCase: "none",
    textDecoration: "none",
  },
  "caption-1": {
    fontFamily: "Inter",
    fontWeight: 500,
    lineHeight: "1rem",
    fontSize: "0.75rem",
    letterSpacing: 0,
    paragraphSpacing: 0,
    textCase: "none",
    textDecoration: "none",
  },
  "caption-2": {
    fontFamily: "Inter",
    fontWeight: 400,
    lineHeight: "1rem",
    fontSize: "0.75rem",
    letterSpacing: 0,
    paragraphSpacing: 0,
    textCase: "none",
    textDecoration: "none",
  },
  "code-1": {
    fontFamily: "IBM Plex Mono",
    fontWeight: 400,
    lineHeight: "1.25rem",
    fontSize: "0.875rem",
    letterSpacing: 0,
    paragraphSpacing: 0,
    textCase: "none",
    textDecoration: "none",
  },
  "code-2": {
    fontFamily: "IBM Plex Mono",
    fontWeight: 400,
    lineHeight: "1rem",
    fontSize: "0.75rem",
    letterSpacing: 0,
    paragraphSpacing: 0,
    textCase: "none",
    textDecoration: "none",
  },
  legal: {
    fontFamily: "Inter",
    fontWeight: 400,
    lineHeight: "0.75rem",
    fontSize: "0.625rem",
    letterSpacing: 0,
    paragraphSpacing: 0,
    textCase: "none",
    textDecoration: "none",
  },
};
